version: '3.8'
services:
  
  devcontainer:
    container_name: info-5940-final-project-devcontainer
    build:
      dockerfile: Dockerfile
      target: devcontainer
    environment:
      - TZ=America/New_York
    volumes:
      - '$HOME/.aws:/root/.aws'
      - '.:/workspace'
    env_file:
      - .env
